### ISSUE TITLE
inject后无法打开stash for mac的代理和增强模式

### ISSUE THREAD

**Issue by Meteors27** [wibus-wee/InjectGUI#15]
### Describe the bug

stash for mac在inject之前能正常打开系统代理和增强模式，inject之后就不行了。

### Reproduction

null

### System Info

```Shell
System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1
    Memory: 51.55 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.1 - /opt/homebrew/bin/node
    npm: 10.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Safari: 18.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by QiuChenly** [comment]
该问题需要进一步测试才能定位。

**Comment by wibus-wee** [comment]
这似乎在最新版已经被解决了～

**Comment by Meteors27** [comment]
感谢大佬！
