### ISSUE TITLE
[Bug] Error when injecting Setapp

### ISSUE THREAD

**Issue by ZhangTongXiang** [wibus-wee/InjectGUI#34]
### Error Message

```
Password:sh: /var/folders/0x/k89rkn350wjf3slc1h__52x80000gn/T/TemporaryItems/NSIRD_InjectGUI_P6aDMm/Setapps/setapp.sh: No such file or directory

```

### Info

- Name: Setapp
- Identifier: com.setapp.DesktopClient
- Setapp Version: 86
- Stage: 正在处理额外的Shell
- InjectGUI version: 1.2.2

**Comment by wibus-wee** [comment]
same as #27

**Comment by ZhangTongXiang** [comment]
thanks but the beta version is not support my mac montery12.5

**Comment by wibus-wee** [comment]
Are you unable to run it after downloading it? The minimum running version I set is already macOS 12.0.

**Comment by ZhangTongXiang** [comment]
yes the icon is not support
my device is x86

**Comment by wibus-wee** [comment]
OK, I have found the problem, please wait for me to fix it

**Comment by ZhangTongXiang** [comment]
thanks clap！！！

**Comment by wibus-wee** [comment]
i may open a new PR for the issue you are facing in the future

at this stage, you may need to try a few more times and check whether your device can access GitHub resources normally

**Comment by ZhangTongXiang** [comment]
ok i will test again while you build the new version

**Comment by wibus-wee** [comment]
hi, I have submitted a fix

**Comment by ZhangTongXiang** [comment]
ok

**Comment by ZhangTongXiang** [comment]
try the new build version only not inject the setapp the same print as issue

**Comment by wibus-wee** [comment]
i subjectively think that this is your network problem that prevents you from downloading resources properly.

Another reason is that i did not properly handle errors in the program when requesting remote resources, which resulted in the script that was not successfully downloaded still being attempted to execute
