### ISSUE TITLE
[Bug] Error when injecting CleanMyMac X

### ISSUE THREAD

**Issue by Alex92748** [wibus-wee/InjectGUI#36]
### Error Message

```
Password:tccutil: Usage: tccutil reset SERVICE [BUNDLE_ID]

```

### Info

- Name: CleanMyMac X
- Identifier: com.macpaw.CleanMyMac4
- CleanMyMac X Version: 41503.0.2404101324
- Stage: 正在处理 Tccutil
- InjectGUI version: 1.2.2

**Comment by wibus-wee** [comment]
same as #24 #26
