### ISSUE TITLE
[Bug] Error when injecting Proxyman

### ISSUE THREAD

**Issue by WithoutCause** [wibus-wee/InjectGUI#37]
### Error Message

```
请同意隐私安全后,重新运行
```

### Info

- Name: Proxyman
- Identifier: com.proxyman.NSProxy
- Proxyman Version: 50800
- Stage: 正在复制可执行文件作为备份
- InjectGUI version: 1.2.2

**Comment by wibus-wee** [comment]
认真看它叫你干什么

看不到你就去设置的隐私与安全里面找到 App 管理，把 InjectGUI 加上去
