### ISSUE TITLE
ProxyMan注入后无法打开

### ISSUE THREAD

**Issue by WithoutCause** [wibus-wee/InjectGUI#38]
### Describe the bug

- App: ProxyMan
- 版本：5.8.9
- 表现：注入成功后，打开 App 只是闪一下，打不开。
- 芯片：M2
- 系统版本：版本14.4.1 (23E224)
<img width="655" alt="image" src="https://github.com/user-attachments/assets/01343e35-922b-4840-8544-8ca59e5286e2">

### Reproduction

使用最新版本注入

### System Info

```Shell
- 芯片：M2
- 系统版本：MacOS Sonoma 版本14.4.1 (23E224)
```

### Used Package Manager

n/a

### Validations

- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wibus-wee** [comment]
上游库的问题，和软件本体无关，等待上游修复
