### ISSUE TITLE
Version 16.0 beta 4 (16A5211f) sudo command, Operation not permitted!

### ISSUE THREAD

**Issue by HolmesZhao** [wibus-wee/InjectGUI#8]
### Describe the bug

xattr: [Errno 1] Operation not permitted: '/Applications/iShot.app/Contents/Frameworks/PTHotKey.framework/Versions/A/PTHotKey' 

后面用大佬编译好的 mac app 也是一样的问题

### Reproduction

No

### System Info

```Shell
System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M3
    Memory: 119.94 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 18.0
    Safari Technology Preview: 17.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by QiuChenly** [comment]
这个一般是你没有给App操作权限导致的。
一般来说你用脚本的话也会遇到这个问题，但是右上角系统会显示消息让你点允许，估计你这个是没点还是什么的。

**Comment by wibus-wee** [comment]
是和权限相关的问题，但是我也没琢磨透哪一个环节的问题

在一部分机型上会出现问题，在不同机子上无法稳定复现... emm 只能转回使用 TUI 版本了暂时

**Comment by wibus-wee** [comment]
目前碰到的问题是这样的：

```applescript
# 可以执行，并且执行成功
do shell script "cp /Applications/Downie\\ 4.app/Contents/Frameworks/Paddle.framework/Versions/A/Paddle /Applications/Downie\\ 4.app/Contents/Frameworks/Paddle.framework/Versions/A/Paddle.backup"

# 不可以执行，会报错
do shell script "cp /Applications/Downie\\ 4.app/Contents/Frameworks/Paddle.framework/Versions/A/Paddle /Applications/Downie\\ 4.app/Contents/Frameworks/Paddle.framework/Versions/A/Paddle.backup" with administrator privileges
# cp: /Applications/Downie 4.app/Contents/Frameworks/Paddle.framework/Versions/A/Paddle.backup: Operation not permitted
```

有必要的情况下，也许就得做个开关了... 我这几天再查查资料是什么问题

**Comment by HolmesZhao** [comment]
好的~还有一个现象就是我给了 sandbox 权限, 就连 sudo 都过不去, 开启 app 后的输入密码
![image](https://github.com/user-attachments/assets/3d0a410d-2d54-404e-b5bc-0da57f62d8c7)

**Comment by HolmesZhao** [comment]
> 系统会显示消息让你点允许，估计你这个是没点还是什

可是并没有任何提醒🤣

**Comment by wibus-wee** [comment]
为什么要开 Sandbox 呢？Sandbox 限制了很多东西，包括目前所依赖的 AppleScript

我记得InjectGUI的Sandbox是关着的啊？

**Comment by HolmesZhao** [comment]
> 为什么要开 Sandbox 呢？Sandbox 限制了很多东西，包括目前所依赖的 AppleScript
> 
> 我记得InjectGUI的Sandbox是关着的啊？

是关闭的, 但是我运行后, inject 那些工具都没有, 需要从网络上下载, 我就寻思是不是 sandbox 里面的 network 没有开导致的, 尝试一下🤣

**Comment by wibus-wee** [comment]
这是肯定的，GUI 并不打算和 InjectLib 强绑定，在未检索到可执行文件的时候会自动下载。

如果你开了 Sandbox 的话那就更没有了，因为开启和未开启储存目录是两个截然不同的目录

**Comment by HolmesZhao** [comment]
> 因为开启和未开启储存目录是两个截然不同的目录

原来如此....但是我这边直接运行的包没有自动下载...用你的 release 包就会自动下载

**Comment by wibus-wee** [comment]
你的是旧版本的代码吧？我之前设置了 DEBUG 状态下不主动下载工具的，不过现在都是一套逻辑了，本地存在的情况下就都不会触发下载

**Comment by HolmesZhao** [comment]
> 你的是旧版本的代码吧？我之前设置了 DEBUG 状态下不主动下载工具的，不过现在都是一套逻辑了，本地存在的情况下就都不会触发下载

两天前的🤣

**Comment by sokach-dev** [comment]
<img width="734" alt="image" src="https://github.com/user-attachments/assets/55d8d4d9-e904-4134-9ada-3e32650963f2">
我也发现权限不行

**Comment by wibus-wee** [comment]
目前在通过实现一个helper来解决这件事情👀

**Comment by birdmichael** [comment]
cp: /Applications/Proxyman.app/Contents/Frameworks/Moya.framework/Versions/A/Moya.backup: Operation not permitted

**Comment by wibus-wee** [comment]
目前所有遇到这个问题的，都只能暂时使用 [TUI version](https://github.com/QiuChenly/InjectLib)

**Comment by birdmichael** [comment]
@wibus-wee 如果通过打开命令行工具去执行呢?
其次,可以获取到注入状态吗? eg:已注入、未注入

**Comment by wibus-wee** [comment]
那如果打开命令行的话，那其实直接用现有的就好了

至于注入状态的话...我只能通过判断一些文件存在或不存在来显示是否注入，这个后面会做

不过当务之急可能是得先把这个权限的问题给搞好... 你可以开一个 feature request 的 issue～

**Comment by HolmesZhao** [comment]
大佬, 你的电脑是不是关闭了 SIP, 我看 Apple Script, 执行 sudo 根本无效啊😂

**Comment by wibus-wee** [comment]
我在一台 SIP on 的机器上试过可以，这就是AppleScript出的问题🥹

**Comment by HolmesZhao** [comment]
是啊...找不到任何资料, 我这边只要是对/Applications 操作就是没有权限, 那个 sudo 根本没生效的感觉

**Comment by birdmichael** [comment]
我应该解决了..但是你需要洁面需要如何优化呢?

**Comment by wibus-wee** [comment]
什么意思？你怎么解决的？

**Comment by birdmichael** [comment]
> 什么意思？你怎么解决的？

推上发你了...我马上提一个初始版本,你审一审..
后面在补充界面和优化逻辑

**Comment by wibus-wee** [comment]
> > 什么意思？你怎么解决的？
> 
> 推上发你了...我马上提一个初始版本,你审一审.. 后面在补充界面和优化逻辑

推好像没看到... 你这是写了一个什么👀

**Comment by birdmichael** [comment]
@wibus_wee 消息都发满了... 哈哈哈

**Comment by HolmesZhao** [comment]
6666

**Comment by HolmesZhao** [comment]
> 我应该解决了..但是你需要洁面需要如何优化呢?

大佬, Process可以执行 sudo 的命令吗? 我看你是换成了Process
